import React from "react";
import Head from "next/head";
import Image from "next/image";

const Deals = ({ providers }) => {
  // console.log(providers);
  return (
    <>
      <div>
        <Head>
          <title>PeapDeal | Deals </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>

   


    </>
  );
};

export default Deals;
