import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { motion  } from "framer-motion";
import { BsFillInfoSquareFill } from "react-icons/bs";

import { Swiper, SwiperSlide } from "swiper/react";
import { Autoplay, Pagination, Navigation } from "swiper";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";

const svgVariants = {
  hidden: { y: 2 },
  visible: {
    rotate: 0,
    transition: { duration: 1, delay: 1 },
  },
};

const pathVariants = {
  hidden: {
    pathLength: 0,
    fill: "rgba(255, 255, 255, 0)"
},
visible: {
  pathLength: 0.5,
  fill: "rgba(255, 255, 255, 1)",
  transition: { duration: 4 }
}
};

export default function Home() {
 
  return (
    <>
      <div>
        <Head>
          <title>PeapDeal | Home </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>

   

<section className="px-3 py-5 bg-neutral-100 lg:py-10">
  <div className="grid lg:grid-cols-2 items-center justify-items-center gap-5">
    <div className="order-2 lg:order-1 flex flex-col justify-center items-center">
      <p className="text-4xl font-bold md:text-7xl text-orange-600">25% OFF</p>
      <p className="text-4xl font-bold md:text-7xl">SUMMER SALE</p>
      <p className="mt-2 text-sm md:text-lg">For limited time only!</p>
      <Link href='/ShoppingList' ><button  className="text-lg md:text-2xl bg-black text-white py-2 px-5 mt-10 hover:bg-zinc-800">Shop Now</button></Link>
    </div>
    <div className="order-1 lg:order-2">
      <img className="h-80 w-80 object-cover lg:w-[500px] lg:h-[500px]" src="https://images.unsplash.com/photo-1615397349754-cfa2066a298e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1887&q=80" alt=""/>
    </div>
  </div>
</section>
      <div className=" flex gap-4 justify-center w-full font-semibold  text-black xl:h-16 lg:h-12 md:h-10 sm:h-8 xl:text-4xl lg:text-2xl md:text-xl sm:text-lg text-center  xl:mt-20 lg:mt-16 md:mt-12 mt-6 ">
      

        <h1>Categories</h1>
      </div>
      <div className="  ">
        <Swiper
          spaceBetween={20}
          centeredSlides={true}
          autoplay={{
              delay: 2500,
              disableOnInteraction: false,
          }}
          // pagination={{
          //   clickable: true,
          // }}
          slidesPerView={3}
          scrollbar={{ draggable: true }}
          // navigation={true}
          // max-h-52 xl:max-h-[500px]
          modules={[Autoplay, Pagination, Navigation]}
          className="mySwiper    xl:w-[1200px] "
        >
          {/* xl:w-auto w-36 lg:w-60 md:w-52 */}
          <SwiperSlide>
            <div className=" xl:border-0 border rounded-lg ">
              <Image
                width={1000}
                height={1000}
                layout="responsive"
                className="rounded-lg"
                quality={100}
                src="/images/resto.png"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            {/* xl:w-[700px] lg:w-[550px] md:w-[450px] w-[300px] */}
            <div className=" xl:border-0 border rounded-lg ">
              <Image
                width={1000}
                height={1000}
                layout="responsive"
                className="rounded-lg"
                quality={100}
                src="/images/grocery.png"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div className="  xl:border-0 border rounded-lg   ">
              <Image
                width={1000}
                height={1000}
                layout="responsive"
                className="rounded-lg"
                quality={100}
                src="/images/health.png"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            {/* xl:w-[700px] lg:w-[550px] md:w-[450px] w-[300px] */}
            <div className=" xl:border-0 border rounded-lg  ">
              <Image
                width={1000}
                height={1000}
                layout="responsive"
                className="rounded-lg"
                quality={100}
                src="/images/tech.png"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div className=" xl:border-0 border rounded-lg  ">
              <Image
                width={1000}
                height={1000}
                layout="responsive"
                className="rounded-lg"
                quality={100}
                src="/images/travel.png"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            {/* xl:w-[700px] lg:w-[550px] md:w-[450px] w-[300px] */}
            <div className=" xl:border-0 border rounded-lg  ">
              <Image
                width={1000}
                height={1000}
                layout="responsive"
                className="rounded-lg"
                quality={100}
                src="/images/serveces.png"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            {/* xl:w-[700px] lg:w-[550px] md:w-[450px] w-[300px] */}
            <div className="xl:border-0 border rounded-lg ">
              <Image
                width={1000}
                height={1000}
                layout="responsive"
                className="rounded-lg"
                quality={100}
                src="/images/MM.png"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            {/* xl:w-[700px] lg:w-[550px] md:w-[450px] w-[300px] */}
            <div className="xl:border-0 border rounded-lg ">
              <Image
                width={1000}
                height={1000}
                layout="responsive"
                className="rounded-lg"
                quality={100}
                src="/images/pet.png"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            {/* xl:w-[700px] lg:w-[550px] md:w-[450px] w-[300px] */}
            <div className="xl:border-0 border rounded-lg">
              <Image
                width={1000}
                height={1000}
                layout="responsive"
                className="rounded-lg"
                quality={100}
                src="/images/gaming.png"
              />
            </div>
          </SwiperSlide>
        </Swiper>
      </div>

      <section className="bg-white dark:bg-gray-900">
    <div className="gap-16 items-center py-8 px-4 mx-auto max-w-screen-xl lg:grid lg:grid-cols-2 lg:py-16 lg:px-6">
        <div className="font-light text-gray-500 sm:text-lg dark:text-gray-400">
            <h2 className="mb-4 text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">We didn't reinvent the wheel</h2>
            <p className="mb-4">We are strategists, designers and developers. Innovators and problem solvers. Small enough to be simple and quick, but big enough to deliver the scope you want at the pace you need. Small enough to be simple and quick, but big enough to deliver the scope you want at the pace you need.</p>
            <p>We are strategists, designers and developers. Innovators and problem solvers. Small enough to be simple and quick.</p>
        </div>
        <div className="grid grid-cols-2 gap-4 mt-8">
            <img className="w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/content/office-long-2.png" alt="office content 1"/>
            <img className="mt-4 w-full lg:mt-10 rounded-lg" src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/content/office-long-1.png" alt="office content 2"/>
        </div>
    </div>
</section>

  
    </>
  );
}
