import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { motion  } from "framer-motion";
import { BsFillInfoSquareFill } from "react-icons/bs";

import { Swiper, SwiperSlide } from "swiper/react";
import { Autoplay, Pagination, Navigation } from "swiper";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";

const svgVariants = {
  hidden: { y: 2 },
  visible: {
    rotate: 0,
    transition: { duration: 1, delay: 1 },
  },
};

const pathVariants = {
  hidden: {
    pathLength: 0,
    fill: "rgba(255, 255, 255, 0)"
},
visible: {
  pathLength: 0.5,
  fill: "rgba(255, 255, 255, 1)",
  transition: { duration: 4 }
}
};

export default function Home() {
  return (
    <>
      <div>
        <Head>
          <title>PeapDeal | Home </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>

      <div className="relative w-full">
        <div className=" absolue xl:w-[800px] xl:h-[800px]  h-96  ">
          <div className="   ">
            <Image
              src="/S1.jpg"
              layout="fill"
              objectFit="cover"
              quality={100}
            />
          </div>
          <div className="w-full h-full flex-col flex absolute top-0 left-0 justify-center items-center">
            <div className=" w-full h-full absolute "></div>
            <div className="App">
              <motion.h1
                className="text-white xl:text-4xl lg:text-2xl  md:text-xl sm:text-lg  font-serif"
                
                animate={{ y: 0, opacity: 1}}
                transition={{
                  duration: 1,
                delay: 0.5
                
                }}
                initial={{ opacity: 0, y: 10 }}
                whileHover={{ scale: 1.2 }}
              >
                save money with eQtOsi.Com 
              </motion.h1>
            </div>

            <form className="absolute xl:bottom-52 bottom-20">
              <label className="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-gray-300">
                Search
              </label>
              <div className="relative xl:w-96 w-26 lg:w-80 ">
                <div className="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
                  <svg
                    aria-hidden="true"
                    className="w-5 h-5 text-gray-500 dark:text-gray-400"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
                    ></path>
                  </svg>
                </div>
                <input
                  type="search"
                  id="default-search"
                  className="block p-4 pl-10 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-white dark:border-gray-600 dark:placeholder-gray-400 dark:text-black dark:focus:ring-blue-500 dark:focus:border-blue-500"
                  placeholder="Search..."
                  required=""
                />
                <button
                  type="submit"
                  className="text-white absolute right-2 bottom-2 bg-slate-700 hover:bg-slate-800 focus:ring-4 focus:outline-none focus:ring-slate-300 font-medium rounded-lg text-sm xl:px-4 px-2 py-2 dark:bg-slate-600 dark:hover:bg-slate-700 dark:focus:ring-slate-800"
                >
                  Search
                </button>
              </div>
            </form>

            <Link href="/Deals">
              <button className="absolute hover:shadow-lg transition duration-500 transform-gpu hover:scale-110 bottom-4 xl:bottom-10 sm:bottom-2   bg-white text-black font-bold py-2 px-4 xl:text-3xl xl:py-4 xl:px-14 lg:text-2xl lg:py-4 lg:px-6 md:text-xl md:px-8 md:py-4  rounded-xl">
                see our best deals
              </button>
            </Link>
          </div>
        </div>
      </div>

      <div className=" flex gap-4 justify-center w-full bg-gradient-to-l from-slate-500 to-black text-white xl:h-16 lg:h-12 md:h-10 sm:h-8 xl:text-4xl lg:text-2xl md:text-xl sm:text-lg text-center  xl:mt-20 lg:mt-16 md:mt-12 mt-6 ">
      {/* <svg
      xmlns="http://www.w3.org/2000/svg"
      width="64"
      height="64"
      enableBackground="new 0 0 64 64"
      viewBox="0 0 64 64"
    >
      <motion.path variants={pathVariants} initial='hidden' animate='visible' d="M33.9 61C18 61 5 48 5 32S18 3 33.9 3c10.2 0 19.8 5.5 25 14.4.3.4.1 1-.3 1.3-.4.3-1 .3-1.3-.1C53.7 15 49 13 43.9 13 33.5 13 25 21.5 25 32s8.5 19 18.9 19c5.1 0 9.9-2 13.4-5.6.4-.4.9-.4 1.3-.1.4.3.5.9.3 1.3-5.2 8.9-14.8 14.4-25 14.4zm0-56C19.1 5 7 17.1 7 32s12.1 27 26.9 27c7.3 0 14.3-3 19.3-8.2-2.8 1.4-6 2.2-9.3 2.2C32.4 53 23 43.6 23 32s9.4-21 20.9-21c3.3 0 6.4.8 9.3 2.2C48.2 8 41.2 5 33.9 5z"></motion.path>
    </svg> */}
        <h1>Categories</h1>
      </div>
      <div className="  ">
        <Swiper
          spaceBetween={20}
          centeredSlides={true}
          autoplay={{
              delay: 2500,
              disableOnInteraction: false,
          }}
          // pagination={{
          //   clickable: true,
          // }}
          slidesPerView={3}
          scrollbar={{ draggable: true }}
          // navigation={true}
          // max-h-52 xl:max-h-[500px]
          modules={[Autoplay, Pagination, Navigation]}
          className="mySwiper    xl:w-[1200px] "
        >
          {/* xl:w-auto w-36 lg:w-60 md:w-52 */}
          <SwiperSlide>
            <div className=" xl:border-0 border rounded-lg ">
              <Image
                width={1000}
                height={1000}
                layout="responsive"
                className="rounded-lg"
                quality={100}
                src="/images/resto.png"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            {/* xl:w-[700px] lg:w-[550px] md:w-[450px] w-[300px] */}
            <div className=" xl:border-0 border rounded-lg ">
              <Image
                width={1000}
                height={1000}
                layout="responsive"
                className="rounded-lg"
                quality={100}
                src="/images/grocery.png"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div className="  xl:border-0 border rounded-lg   ">
              <Image
                width={1000}
                height={1000}
                layout="responsive"
                className="rounded-lg"
                quality={100}
                src="/images/health.png"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            {/* xl:w-[700px] lg:w-[550px] md:w-[450px] w-[300px] */}
            <div className=" xl:border-0 border rounded-lg  ">
              <Image
                width={1000}
                height={1000}
                layout="responsive"
                className="rounded-lg"
                quality={100}
                src="/images/tech.png"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div className=" xl:border-0 border rounded-lg  ">
              <Image
                width={1000}
                height={1000}
                layout="responsive"
                className="rounded-lg"
                quality={100}
                src="/images/travel.png"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            {/* xl:w-[700px] lg:w-[550px] md:w-[450px] w-[300px] */}
            <div className=" xl:border-0 border rounded-lg  ">
              <Image
                width={1000}
                height={1000}
                layout="responsive"
                className="rounded-lg"
                quality={100}
                src="/images/serveces.png"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            {/* xl:w-[700px] lg:w-[550px] md:w-[450px] w-[300px] */}
            <div className="xl:border-0 border rounded-lg ">
              <Image
                width={1000}
                height={1000}
                layout="responsive"
                className="rounded-lg"
                quality={100}
                src="/images/MM.png"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            {/* xl:w-[700px] lg:w-[550px] md:w-[450px] w-[300px] */}
            <div className="xl:border-0 border rounded-lg ">
              <Image
                width={1000}
                height={1000}
                layout="responsive"
                className="rounded-lg"
                quality={100}
                src="/images/pet.png"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            {/* xl:w-[700px] lg:w-[550px] md:w-[450px] w-[300px] */}
            <div className="xl:border-0 border rounded-lg">
              <Image
                width={1000}
                height={1000}
                layout="responsive"
                className="rounded-lg"
                quality={100}
                src="/images/gaming.png"
              />
            </div>
          </SwiperSlide>
        </Swiper>
      </div>

      <div className="flex items-center mt-20 bg-white text-gray-800">
        <div className="p-4 w-full">
          <div className="grid grid-cols-12 gap-4">
            <div className="col-span-12 sm:col-span-6 md:col-span-3">
              <div className="grid grid-rows-1 gap-4 content-start bg-white shadow-sm hover:shadow-xl rounded p-4">
                <div className="flex items-center justify-center flex-shrink-0  rounded-xl  ">
                  <BsFillInfoSquareFill className="md:h-10 md:w-10 h-6 w-6 text-blue-500" />
                </div>
                <div className="flex flex-col  ml-4 text-center">
                  <div className="text-sm text-gray-500">Infos</div>
                  <div className=" sm:text-sm md:text-lg  font-sans">
                    With eqtosi.com, finding great deals at Expedia and applying
                    them to your purchases is faster, more convenient, and
                    ultimately guarantees greater savings.
                  </div>
                </div>
              </div>
            </div>
            <div className="col-span-12 sm:col-span-6 md:col-span-3">
              <div className="grid grid-rows-1 gap-4 content-start bg-white shadow-sm hover:shadow-xl rounded p-4">
                <div className="flex items-center justify-center flex-shrink-0  rounded-xl  ">
                  <BsFillInfoSquareFill className="md:h-10 md:w-10 h-6 w-6 text-green-500" />
                </div>
                <div className="flex flex-col flex-grow ml-4 text-center">
                  <div className="text-sm text-gray-500">Infos</div>
                  <div className="font-sans sm:text-sm md:text-lg ">
                    Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                    Doloremque tempora ullam iusto, cum blanditiis facere
                    inventore ratione ipsum, ea minima minus odio, provident
                    rerum officiis error placeat recusandae iure. Animi. Get
                    notified when your saved item goes on sale; just set the
                    price you would like to pay! <br /> <br />
                  </div>
                </div>
              </div>
            </div>
            <div className="col-span-12 sm:col-span-6 md:col-span-3">
              <div className="grid grid-rows-1 gap-4 content-start bg-white shadow-sm hover:shadow-xl rounded p-4">
                <div className="flex items-center justify-center flex-shrink-0  rounded-xl  ">
                  <BsFillInfoSquareFill className="md:h-10 md:w-10 h-6 w-6 text-orange-500" />
                </div>
                <div className="flex flex-col flex-grow ml-4 text-center">
                  <div className="text-sm text-gray-500">Infos</div>
                  <div className="font-sans sm:text-sm md:text-lg  ">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Illum dolore dolorem aliquam deleniti veniam laudantium,
                    cumque laborum officiis porro obcaecati eaque sequi
                    architecto temporibus beatae praesentium dicta atque error
                    necessitatibus?
                  </div>
                </div>
              </div>
            </div>
            <div className="col-span-12 sm:col-span-6 md:col-span-3">
              <div className="grid grid-rows-1 gap-4 content-start bg-white shadow-sm hover:shadow-xl rounded p-4">
                <div className="flex items-center justify-center flex-shrink-0  rounded-xl  ">
                  <BsFillInfoSquareFill className="md:h-10 md:w-10 h-6 w-6 text-red-500" />
                </div>
                <div className="flex flex-col flex-grow ml-4 text-center">
                  <div className="text-sm text-gray-500">Infos</div>
                  <div className="font-sans sm:text-sm md:text-lg ">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Illum dolore dolorem aliquam deleniti veniam laudantium,
                    cumque laborum officiis porro obcaecati eaque sequi
                    architecto temporibus beatae praesentium dicta atque error
                    necessitatibus?
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
